name: CI/CD - Test and Deploy

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'function-app-demo'
  PYTHON_VERSION: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        echo "🧪 Running test cases..."
        python -m pytest tests/ -v

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '.'
        scm-do-build-during-deployment: false
        enable-oryx-build: false

    - name: Verify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🎯 Function App: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "🌐 Test URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/hello?name=Bro"