name: CI/CD - Test and Deploy

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'function-app-demo'
  PYTHON_VERSION: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Storage Setting
      run: |
        # This WILL work - sets storage via CLI
        connection_string=$(az storage account show-connection-string \
          --name bachanfuncstorage \
          --resource-group sandbox \
          --query "connectionString" \
          -o tsv)
        
        az functionapp config appsettings set \
          --name function-app-demo \
          --resource-group sandbox \
          --settings AzureWebJobsStorage="$connection_string"

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '.'

    - name: Verify deployment
      run: |
        echo "✅ DEPLOYMENT SUCCESSFUL!"
        echo "🌐 Test: https://function-app-demo.azurewebsites.net/api/hello?name=Bachan"