name: CI/CD - Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'function-app-demo'
  PYTHON_VERSION: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        echo "🧪 Running all test cases..."
        python -m pytest tests/ -v
      continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure
    needs: test  # ⬅️ This ensures tests run first and must pass
    if: github.ref == 'refs/heads/main'  # ⬅️ Only deploy on main branch
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '.'
        scm-do-build-during-deployment: false
        enable-oryx-build: false

    - name: Verify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Function App: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "Trigger URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/hello"